# Generated by Django 3.1.5 on 2021-01-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_privce', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book_date', models.DateField()),
            ],
        ),
    ]
